/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gleo.plugins.ravenbox.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the AnnouncementImage service. Represents a row in the &quot;ravenbox_AnnouncementImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.gleo.plugins.ravenbox.model.impl.AnnouncementImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.gleo.plugins.ravenbox.model.impl.AnnouncementImageImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see AnnouncementImage
 * @see com.gleo.plugins.ravenbox.model.impl.AnnouncementImageImpl
 * @see com.gleo.plugins.ravenbox.model.impl.AnnouncementImageModelImpl
 * @generated
 */
@ProviderType
public interface AnnouncementImageModel extends BaseModel<AnnouncementImage>,
	LocalizedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a announcement image model instance should use the {@link AnnouncementImage} interface instead.
	 */

	/**
	 * Returns the primary key of this announcement image.
	 *
	 * @return the primary key of this announcement image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this announcement image.
	 *
	 * @param primaryKey the primary key of this announcement image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the announcement image ID of this announcement image.
	 *
	 * @return the announcement image ID of this announcement image
	 */
	public long getAnnouncementImageId();

	/**
	 * Sets the announcement image ID of this announcement image.
	 *
	 * @param announcementImageId the announcement image ID of this announcement image
	 */
	public void setAnnouncementImageId(long announcementImageId);

	/**
	 * Returns the company ID of this announcement image.
	 *
	 * @return the company ID of this announcement image
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this announcement image.
	 *
	 * @param companyId the company ID of this announcement image
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this announcement image.
	 *
	 * @return the group ID of this announcement image
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this announcement image.
	 *
	 * @param groupId the group ID of this announcement image
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this announcement image.
	 *
	 * @return the user ID of this announcement image
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this announcement image.
	 *
	 * @param userId the user ID of this announcement image
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this announcement image.
	 *
	 * @return the user uuid of this announcement image
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this announcement image.
	 *
	 * @param userUuid the user uuid of this announcement image
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the announcement ID of this announcement image.
	 *
	 * @return the announcement ID of this announcement image
	 */
	public long getAnnouncementId();

	/**
	 * Sets the announcement ID of this announcement image.
	 *
	 * @param announcementId the announcement ID of this announcement image
	 */
	public void setAnnouncementId(long announcementId);

	/**
	 * Returns the file entry ID of this announcement image.
	 *
	 * @return the file entry ID of this announcement image
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this announcement image.
	 *
	 * @param fileEntryId the file entry ID of this announcement image
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the description of this announcement image.
	 *
	 * @return the description of this announcement image
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this announcement image in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this announcement image
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this announcement image in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this announcement image. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this announcement image in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this announcement image
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this announcement image in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this announcement image
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this announcement image.
	 *
	 * @return the locales and localized descriptions of this announcement image
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this announcement image.
	 *
	 * @param description the description of this announcement image
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this announcement image in the language.
	 *
	 * @param description the localized description of this announcement image
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this announcement image in the language, and sets the default locale.
	 *
	 * @param description the localized description of this announcement image
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this announcement image from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this announcement image
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this announcement image from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this announcement image
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the order of this announcement image.
	 *
	 * @return the order of this announcement image
	 */
	public int getOrder();

	/**
	 * Sets the order of this announcement image.
	 *
	 * @param order the order of this announcement image
	 */
	public void setOrder(int order);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(AnnouncementImage announcementImage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AnnouncementImage> toCacheModel();

	@Override
	public AnnouncementImage toEscapedModel();

	@Override
	public AnnouncementImage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}